image: vigneshv59/gallery-firebase
stages:
  - one
  - two
jobs:
  echo:
    script:
      - echo "hi"
      - bash -c 'for run in {1..100}; do echo hello$run; done'
    stage: one
  echotwo:
    script:
      - bash -c 'for run in {1..100}; do echo 'hello2'; done'
    stage: one
  final:
    script:
      - firebase use $GOOGLE_PROJECT_ID
      - firebase deploy
    stage: two
